version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specifies the Dockerfile to build the image
    container_name: bbl-crud-app
    ports:
      - "8080:8080"  # Map port 8080 of the container to port 8080 on the host
    depends_on:
      - db  # Ensure db service is started before the app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: bbl-crud-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist the database data
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432
    networks:
      - app-network

volumes:
  postgres-data:
    driver: local

networks:
  app-network:
    driver: bridge
